### ISSUE TITLE
Error in  Protect and call a web API on Azure AD 'invalid client id'

### ISSUE THREAD

**Issue by Lawliet0727** [Azure-Samples/ms-identity-javascript-angular-tutorial#11]
# Error "invalid_client: 70002 - [2021-07-29 11:26:28Z]: AADSTS70002: The provided request must include a 'client_secret' input parameter"

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [X ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ]   4) Deploy to Azure Storage and App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call a multi-tenant web API
    - [ ] 7-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 7-2) Call a web API using Proof of Possession tokens
```

## This issue is for a

```console
    - [X ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce
-login button
-after I redirect in microsoft login and successfully authenticated , it redirects me again in the homepage  
>

### Any log messages given by the failure
invalid_client: 70002 - [2021-07-29 11:26:28Z]: AADSTS70002: The provided request must include a 'client_secret' input parameter Trace ID: cb197be3-0850-4322-82b1-c18a4b480f00
Correlation ID: be4946fd-1a44-46b6-ad2e-345a1b09bdfa
Timestamp: 2021-07-29 11:26:28Z - Correlation ID: be4946fd-1a44-46b6-ad2e-345a1b09bdfa - Trace ID: cb197be3-0850-4322-82b1-c18a4b480f00
>

### Expected/desired behavior

>

### Library version

>

### Browser and version

> Chrome, Edge, Firefox, Safari?

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@Lawliet0727 looks like this is an app registration issue. Can you please confirm that, on **Azure portal** > **App Registration** > **Your app** > **Authentication**, the app is registered as "single page application", not "web"?

**Comment by Lawliet0727** [comment]
> @Lawliet0727 looks like this is an app registration issue. Can you please confirm that, on **Azure portal** > **App Registration** > **Your app** > **Authentication**, the app is registered as "single page application", not "web"?

This is correct, the issue now are resolved I mistakenly register my app as "Web" and when I changed it on "SPA" it working fine.

Thanks @derisen
