### ISSUE TITLE
What is the purpose of AzureAd:Roles in appsettings.json?

### ISSUE THREAD

**Issue by markp24** [Azure-Samples/ms-identity-javascript-angular-tutorial#150]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ]   4) Deploy to Azure Storage and App Service
    - [ x] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call a multi-tenant web API
    - [ ] 7-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 7-2) Call a web API using Proof of Possession tokens
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [x ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

"AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "Enter the domain of your Azure AD tenant, e.g. 'contoso.onmicrosoft.com'",
    "TenantId": "Enter the ID of your Azure AD tenant copied from the Azure portal",
    "ClientId": "Enter the application ID (clientId) of the 'TodoListAPI' application copied from the Azure portal",
    "Roles": {
      "TaskAdmin": "TaskAdmin",
      "TaskUser": "TaskUser"
    }

In the API configuration files (appsettings.json / appsettings.Development.json), does the Roles section within AzureAd in as shown above serve any purpose? 

The sample app looks to be using the AppRole static class to get role names so I'm wondering if this section is needed in the .json files, and if so where/how is it used?

### Any log messages given by the failure

>

### Expected/desired behavior

>

### Library version

>

### Browser and version

> Chrome, Edge, Firefox, Safari?

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by salman90** [comment]
Hi @markp24 , you're correct. The roles in appsettings.json are not used. I will remove them from the sample. We provide static values to help with the logic for the example provided in the readme. For example, we use the roles in the RoleGuard to specify the user's role that can access the route.

**Comment by salman90** [comment]
@markp24 Thanks
