### ISSUE TITLE
Token for delegated API permission from one application registration to another

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [Azure-Samples/ms-identity-javascript-angular-tutorial#168]
Original question was badly formulated and after a good night's sleep how grab tokens for multiple scopes on different API permissions had nothing to do with the 2-Authorization, 1-call-graph sample.  Sorry.

**Comment by MatthewDavidCampbell** [comment]
Issue can be deleted.

**Comment by salman90** [comment]
@MatthewDavidCampbell no worries, please let us know if you face any additional challenges
