### ISSUE TITLE
When using the MSALGuard and RoleGuard on a route, the Role guard will allow access even if the user does not have the correct role

### ISSUE THREAD

**Issue by Depechie** [Azure-Samples/ms-identity-javascript-angular-tutorial#180]
# Issue

When using the MSALGuard and RoleGuard on a route, the Role guard will allow access even if the user does not have the correct role!
This is due to the fact that there is no guard sequence in Angular.

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ]   4) Deploy to Azure Storage and App Service
    - [x] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call a multi-tenant web API
    - [ ] 7-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 7-2) Call a web API using Proof of Possession tokens
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [x] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

Change the sample so that the root of the app also needs the MSALGuard, this will trigger the login sequence as soon as someone uses the website. In other words no need for the LOGIN button.
Open a new InPrivate windows and navigate straight to an URL that has both guards active.
If there was no previous login, the user is redirected to the Azure AD login flow, BUT the RoleGuard already finished it's check and returned TRUE ( https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/blob/main/5-AccessControl/1-call-api-roles/SPA/src/app/role-guard.service.ts#L34 ).
Due to the fact that there were no accounts available yet.

After the login flow of Azure AD the Role guard is no longer checked and the user is presented with the URL he typed in, although he should not be able to see it.

### Expected/desired behavior

Role checks can only be done after an account has been acquired AND should be done each time!

### Library version

msal-angular: ^2.1.2
angular 13 & 14

### Browser and version

Edge

### Mention any other details that might be useful

I know this is a limitation of Angular ( there is no guard replay or guard order ), but this Role check example should compensate for this somehow. Because if we want to use role guarding, it should always be checked when we have the user roles available.

**Comment by derisen** [comment]
@Depechie thank you so much for catching this. Let me try to reproduce it and get back to you.

**Comment by Depechie** [comment]
Comment for getting out off the stale bot

**Comment by Depechie** [comment]
Hey @derisen so I uploaded a basic sample here: https://github.com/SanITy-BV/BirdAtlas-frontend/tree/guard
I also recorded the logging with an animated gif, you can follow along here: https://raw.githubusercontent.com/SanITy-BV/BirdAtlas-frontend/guard/Animation.gif

So when the app is first started, the MSAL guard will kick in and do a redirect to the login flow, this works perfectly. But when that flow is done, you will see the begin screen of the web app.
This is due to the fact that the 2 gaurds are already passed at the same time during initial startup. You will notice in the console logging that the Role guard thinks no account is available ( this is true we are not yet logged in at that time due to the MSAL guard still needs to kick in ) and that no check can be done..

If you then just refresh the page, the same 2 guards are processed and now the Role guard has enough info to actually do the processing and will show that there is an account and the guard check has been done.

I hope this explains my issue.

**Comment by derisen** [comment]
thanks @Depechie looking at this now -will get back

**Comment by derisen** [comment]
@Depechie apologies for the late response, we've been unusually busy these days. I can reproduce this with the repo you shared. It seems this is simply not a scenario we've considered i.e. enabling `RoleGuard` for the main route where the user signs into. 

My understanding is that, in the sample from this repo, when a user hits a component route that has `MsalGuard` and `RoleGuard` enabled (like `http://localhost:4200/dashboard`), she will prompted for sign-in via `MsalGuard`, and then after sign-in will be redirected to the main route first `http://localhost:4200/` (which doesn't have `RoleGuard`), and then will be redirected back to `http://localhost:4200/dashboard`, which at that point account info will be available to `RoleGuard`.

I don't have a solution right now but I will put this to backlog and pick it up first when we start updating the samples in this repo. I'm also not entirely sure if this is a legitimate use case, or rather, the best approach to handle this use case. If the user is simply needed to be in a particular role to sign-in to the application, perhaps [requiring user assignment](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/what-is-access-management#requiring-user-assignment-for-an-app) would be a better way to handle it? 

Nevertheless, if you come up with a solution please feel free to make a PR.

**Comment by Depechie** [comment]
Thanks @derisen for the detailed response! No worries about the actual timing of any samples. At least I'm getting info and am very glad it was not something I did wrong in the setup ( could always have missed something ).

As off the use case, well... we just want to be sure that IF a user get's hold of a url all guards are validated. In our case this also means checking that you are at least in a certain app role. There are several roles and depending on which the main page will look different. Or if you do not have any role assigned you should not be able to see anything.

But I understand this could maybe be solved in another flow/way too.
At least I would like to check the roles 'after' the login and maybe we could redirect to a certain 'not allowed' page?

**Comment by derisen** [comment]
That's fair enough. What I'm thinking is that it might be better to use a single custom guard that combines `MsalGuard` and `RoleGuard`, though I can also see the merit of getting multiple guards to work in tandem. There's an [understanding](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-guard.md) that `MsalGuard` will not only be able to cover all use cases, so this repo should have at least one example of a custom guard to replace it. Let me look into these.  I'll keep this issue open until then -and thank you for all the feedback!

**Comment by Depechie** [comment]
Combining in a single one would be a perfect solution for use!
Not done that though for MSAL, is there an example for that scenario maybe?

**Comment by derisen** [comment]
I'm afraid not at the moment. There was also a [feature request](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3406) for extending `MsalGuard`, but nothing has been delivered on this so far. I suppose you can copy paste the [MsalGuard code](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/src/msal.guard.ts) into a guard and add the role check there, but I'll for sure add an example here eventually.

**Comment by derisen** [comment]
keep open

**Comment by derisen** [comment]
@Depechie this should now be fixed, using a custom guard based on MsalGuard. Thanks again for catching this!

**Comment by Depechie** [comment]
Hey @derisen could you elaborate a bit more?
Has something changed since your original response ( https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/issues/180#issuecomment-1174196604 ), in other words is there now more guidance on creating those custom guards maybe?

Not keeping track of all the MSAL updates, so could be I'm missing obvious of course :)

**Comment by derisen** [comment]
@Depechie of course, my bad. Right now the updated sample is using a [custom guard](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/blob/main/5-AccessControl/1-call-api-roles/SPA/src/app/base.guard.ts) based on MsalGuard (pretty much copy/paste), and then extending it in a [role guard](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/blob/main/5-AccessControl/1-call-api-roles/SPA/src/app/role.guard.ts). Ideally the MsalGuard itself should be extensible, and I'm separately working on a PR to msal-angular for doing just that. That could take a while so for the moment, I think this is the way forward, but I'm open to suggestions.

**Comment by Depechie** [comment]
Thanks! Will take a look as soon as I find some time!

**Comment by Depechie** [comment]
@derisen just wanted to circle back that this works great!
But true, now having that baseGuard directly in our code would be nice to get rid off once the base lib has a guard that is extendable.

**Comment by derisen** [comment]
Sounds great! Still working on making this extensible by default, hopefully will get this in to msal-angular
