### ISSUE TITLE
Forget passeword returns with AADB2C error code

### ISSUE THREAD

**Issue by patolax** [Azure-Samples/ms-identity-javascript-angular-tutorial#197]
When I ran the following sample code, I can login and logout without any issues. However, when I click on "Forgot your password?" link it redirects back with` server_error: AADB2C: An exception has occurred.` see below. 
https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/3-Authorization-II/2-call-api-b2c

![image](https://user-images.githubusercontent.com/29444156/189588716-78b370d5-64af-4635-9470-09e62155dd8a.png)

What is the best way to fix this.

Also, can we initiate rest password flow while the user is logged in (i.e without going to the login page)?

**Comment by derisen** [comment]
@patolax are you using the [self-service password reset flow](https://docs.microsoft.com/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-user-flow#self-service-password-reset-recommended) or [the legacy flow](https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-user-flow#password-reset-policy-legacy)? This sample is using self-service. If you need to work with the legacy flow, please refer to [this sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular-b2c-sample-app) instead.

> Also, can we initiate rest password flow while the user is logged in (i.e without going to the login page)?

This should be possible. You could create a reset password button with the required logic, for example, similar to the edit profile button in the sample I've shared ([see](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/cf19d12246949f9cb99f4853953cbefb7d27009e/samples/msal-angular-v2-samples/angular-b2c-sample-app/src/app/app.component.ts#L198)). 

Let me know if this resolves your issue.

**Comment by patolax** [comment]
Thanks, that resolved both.

If we initiate a password reset from the application and at the b2c reset page user clicks on cancel and subsequently gets redirected to the app, at that point it seems to be user is not authnticated anymore. `"@azure/msal-angular@2.4.2 : Error - Guard - error while logging in, unable to activate"`. None of the routes work, nor api calls.


this error is also logged.

![image](https://user-images.githubusercontent.com/29444156/189781160-69bb54eb-7919-47b0-9119-a9d67c0cd2c2.png)

**Comment by derisen** [comment]
@patolax thanks for catching the error. We apparently didn't handle the exception thrown when the user clicks cancel. Made a note to update the sample for this case.

Regarding the UI, I'm not entirely sure how much of it is customizable. Can you please refer to: [Customize the user interface in Azure Active Directory B2C](https://docs.microsoft.com/azure/active-directory-b2c/customize-ui?pivots=b2c-user-flow)
