### ISSUE TITLE
API Issue - 500 Error

### ISSUE THREAD

**Issue by SilviuMihai** [Azure-Samples/ms-identity-javascript-angular-tutorial#210]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ x] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ]   4) Deploy to Azure Storage and App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-2) Call a multi-tenant web API
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ x] documentation issue or request
```

### Minimal steps to reproduce

So I managed to register a user and log in, but it fails when I am trying to reach the Todo List.(access the API)

### Any log messages given by the failure

An unhandled exception occurred while processing the request.
UriFormatException: Invalid URI: The format of the URI could not be determined.
System.Uri.CreateThis(string uri, bool dontEscape, UriKind uriKind)

UriFormatException: Invalid URI: The format of the URI could not be determined.
System.Uri.CreateThis(string uri, bool dontEscape, UriKind uriKind)
System.Uri..ctor(string uriString)
Microsoft.Identity.Web.AuthorityHelpers.BuildAuthority(MicrosoftIdentityOptions options)
Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions+<>c__DisplayClass3_0.<AddMicrosoftIdentityWebApiImplementation>b__0(JwtBearerOptions options, IServiceProvider serviceProvider, IOptionsMonitor<MicrosoftIdentityOptions> microsoftIdentityOptionsMonitor)
Microsoft.Extensions.Options.ConfigureNamedOptions<TOptions, TDep1, TDep2>.Configure(string name, TOptions options)
Microsoft.Extensions.Options.OptionsFactory<TOptions>.Create(string name)
Microsoft.Extensions.Options.OptionsMonitor<TOptions>+<>c__DisplayClass11_0.<Get>b__0()
System.Lazy<T>.ViaFactory(LazyThreadSafetyMode mode)
System.Lazy<T>.CreateValue()
System.Lazy<T>.get_Value()
Microsoft.Extensions.Options.OptionsCache<TOptions>.GetOrAdd(string name, Func<TOptions> createOptions)
Microsoft.Extensions.Options.OptionsMonitor<TOptions>.Get(string name)
Microsoft.AspNetCore.Authentication.AuthenticationHandler<TOptions>.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, string authenticationScheme)
Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, string scheme)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Expected/desired behavior

>

### Library version

>

### Browser and version

> Chrome, Edge, Firefox, Safari?

Hello, regarding the sample: https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/3-Authorization-II/2-call-api-b2c

In the steps asks at some point: 
Quote: Find the variable scopeRequiredByApi and replace its value with the name of the API scope that you have just exposed (by default demo.read)
The value is what more exactly, the scope name like access_as_user ? 

Also for: 
Find the key Instance and replace the existing value with your Azure AD B2C tenant name.
Find the key Domain and replace the existing value with your Azure AD B2C tenant name.
Is the same thing no ? 
And it should be tenantname.onmicrosoft.com correct ?

>

Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
> Hello, regarding the sample: https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/3-Authorization-II/2-call-api-b2c
> 
> In the steps asks at some point:
> Quote: Find the variable scopeRequiredByApi and replace its value with the name of the API scope that you have just exposed (by default demo.read)
> The value is what more exactly, the scope name like access_as_user ?

That's right, it should be replaced with the scope name (but not the entire scope e.g. `api://xxxxx-xxxx-xxxx-xxxx/access_as_user `vs `access_as_user`)

> Also for:
> Find the key Instance and replace the existing value with your Azure AD B2C tenant name.
> Find the key Domain and replace the existing value with your Azure AD B2C tenant name.
> Is the same thing no ?

They are not the same thing no. 
Instance will be: `tenantname.b2clogin.com `
Domain will be: `tenantname.onmicrosoft.com `

> And it should be tenantname.onmicrosoft.com correct ?

That's right!

> Thanks! We'll be in touch soon.

Sorry for the confusion. Does this help?

**Comment by derisen** [comment]
Thanks for the feedback! Will make sure to update the README to clarify this.
