### ISSUE TITLE
Bearer error="invalid_token", error_description="The signature key was not found"

### ISSUE THREAD

**Issue by peterbomdev** [Azure-Samples/ms-identity-javascript-angular-tutorial#29]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [x ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ]   4) Deploy to Azure Storage and App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call a multi-tenant web API
    - [ ] 7-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 7-2) Call a web API using Proof of Possession tokens
```

## This issue is for a

```console
    - [x] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce
I followed the steps, running the api in two diferent ways: from visual studio using IIS express and from the console as described in the steps. 
>

### Any log messages given by the failure

I'm able to open the page, gets a bearer token, but when accessing the todolist page I get the following errors, two different errors, according to how I run the api:

1. If running from Visual Studio:
401 - Bearer error="invalid_token", error_description="The signature key was not found"

2. If running from a console with "dotnet run":
Err_Cert_Authority_Invalid
>

### Expected/desired behavior
Expected to get access to the todolist page.
>

### Browser and version

> Chrome, Edge, Firefox, Safari?
Chrome, newest (92)

**Comment by peterbomdev** [comment]
Also, when checking my JWT token, the KID (Key Id) is not present in the list I get from:

https://login.microsoftonline.com/{my tenant id}/discovery/v2.0/keys

it is only present when I request:
https://login.microsoftonline.com/{my tenant id}/discovery/v2.0/keys?appid={my api client id}

**Comment by derisen** [comment]
@peterbomdev this is an error I haven't encountered before. As a first step, can you confirm that:

- you have trusted the development certificates ([see](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/3-Authorization-II/1-call-api#step-3-trust-development-certificates))
- you have set the `accessTokenAcceptedVersion` to **2** in your web API registration

Please also share your configuration files for SPA (`auth-config.ts`) and web API projects (`appsettings.json`), masking any client secrets.

**Comment by jeevasusej** [comment]
Yeah, I have gone with hectic days because of this issue. 

Can you please post your client side code?

To be worked as expected, need to use like
Instead of the scope " scopes: ['openid', 'profile', 'User.Read']"
I have used scopes: ['openid', 'api://xxxxxxxxxxx/access_as_user']

User.Read adds nonce. Because of this, the token become invalid.

**Comment by derisen** [comment]
@jeevasusej ok that explains. You were sending the wrong access token to your web API, hence you got the "The signature key was not found" error. `User.Read` is a scope for Microsoft Graph, so the access token you get for that scope won't work for your web API. `api://xxxxxxxxxxx/access_as_user` is the scope you need to get an access token for to be able to call your backend.

When you request an access token, all the scopes you enter should belong to the same resource. If the scopes are mixed, you'll get an access token only for the first one. See [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md) for more.

Let me know if you have any other issue.

**Comment by jeevasusej** [comment]
Yes @derisen. Thank you for your explanation. 
I have mixed the scope and got the token for the graph API not for the web api . That's why I have asked him to post the client side code.
Because of that I have lost many hours to find it. I missed to see your information from the DOC. 

In any case, can we use the token for web api that is intended for the Graph API?

**Comment by derisen** [comment]
@jeevasusej no you can't. You'll need an access token for your web API (the `aud `claim in the token will be the `clientId `of your web API, and `scp `claim will be its scope that you've exposed during app registration).

The sample is already configured to do this. In `auth-config.ts`, we have the `protectedResources `object:

```typscript
export const protectedResources = {
  todoListApi: {
    endpoint: "https://localhost:44351/api/todolist",
    scopes: ["Enter_the_Web_Api_Scope_here"], // e.g. "api://<service-app-client-id>/access_as_user"
  },
}
```

Then in `app.module.ts`, we set `protectedResourceMap` object:

```typescript
export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();

  protectedResourceMap.set(protectedResources.todoListApi.endpoint, protectedResources.todoListApi.scopes);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
```

**Comment by jeevasusej** [comment]
Thank you @derisen

**Comment by derisen** [comment]
Closing this. Let us know if you have any other issues.
