### ISSUE TITLE
untrusted_authority issue when testing the sample with private B2C tenant

### ISSUE THREAD

**Issue by LuisGorla** [Azure-Samples/ms-identity-javascript-angular-tutorial#40]
# Issue

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [X] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ]   4) Deploy to Azure Storage and App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call a multi-tenant web API
    - [ ] 7-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 7-2) Call a web API using Proof of Possession tokens
```

## This issue is for a

```console
    - [X] bug report -> please search issues before submitting
    - [X] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

> Clone the repo, install all dependencies, add B2C tenant information and policies in auth-config.ts

### Any log messages given by the failure

> Dev Tools console error: 

ERROR Error: Uncaught (in promise): ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.

### Expected/desired behavior

>

### Library version

>    "@azure/msal-angular": "^2.0.2",
    "@azure/msal-browser": "^2.16.0"

### Browser and version

> Chrome and Edge

### Mention any other details that might be useful

> I was following the tutorial steps and ran into this issue
![2021-09-16_15h20_08](https://user-images.githubusercontent.com/35284988/133664702-9eaf2048-d449-45f4-9af0-36c376d0952c.png)

**Comment by LuisGorla** [comment]
Maybe this is a dumb question/issue. Sorry in advance if that's the case, I've implemented all the workarounds available by googling, and neither of those worked. 

I've been following the documentation step by step and, as far as I know, I didn't miss any step. 

Regards!

**Comment by derisen** [comment]
hey @LuisGorla, looks like the value you entered for `b2cPolicies.authorityDomain` is wrong -it should be `<yourTenantName>.b2clogin.com` instead of `<yourTenantName>.onmicrosoft.com`. Can you change that and give it a try again?

**Comment by LuisGorla** [comment]
You're right, thank you!
