### ISSUE TITLE
Authorization header not getting added to http PUT and DELETE 

### ISSUE THREAD

**Issue by jag-sekhon** [Azure-Samples/ms-identity-javascript-angular-tutorial#43]
# Issue
Authorization header automatically gets added by HttpInterceptor to GET,POST and OPTIONS but we have to manually add it to PUT and DELETE request. If we don't add "Authorization: 'Bearer ' + token" to PUT and DELETE, then we get 401 Unauthorized error.

Openid-configuration returns Response Headers Allow: OPTIONS,TRACE,GET,HEAD and POST. Will that be an issue? We are using custom policies for this.
![image](https://user-images.githubusercontent.com/95777565/145292222-13cd1237-4ebc-4cfd-9d62-9eacbd713734.png)
 

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [x] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ]   4) Deploy to Azure Storage and App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call a multi-tenant web API
    - [ ] 7-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 7-2) Call a web API using Proof of Possession tokens
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [x] question
    - [ ] feature request
    - [x] documentation issue or request
```

### Minimal steps to reproduce
We are using Angular V 11.2.9 and the latest MSAL npm packages (updated few days back)
"@azure/msal-angular": "^2.0.4",
"@azure/msal-browser": "^2.18.0"
>

### Any log messages given by the failure

>

### Expected/desired behavior

>

### Library version
Angular V 11.2.9
"@azure/msal-angular": "^2.0.4",
"@azure/msal-browser": "^2.18.0"
>

### Browser and version

> Chrome, Edge, Firefox, Safari? 
Chrome Version 96.0.4664.45

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by jag-sekhon** [comment]
Still waiting for response on this one.

**Comment by salman90** [comment]
Hi @jag-sekhon,

Sorry for not getting back to you sooner. Please look at sample [ms-identity-javascript-angular-tutorial/5-AccessControl/1-call-api-roles/](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/5-AccessControl/1-call-api-roles). In this scenario, you will find an example of an Angler (SPA) making (get, post, update, delete) calls to a secure web API.

**Comment by jag-sekhon** [comment]
Hi Salman
    Thank you for replying back about this. We are using same approach to call api's. The issue is automatically adding the Auth/Bearer Token by HttpInterceptor. It gets added to GET,POST and OPTIONS but we have to manually add it to PUT and DELETE request as its not getting added there. We are not able to find out why this is happening or where do we need to set it up. We are using MSAL-Angular and Msal-browser libraries and on B2C side, we have setup custom policies but in those policies we are not able to find any place where we could have blocked these requests. Please let us know where we can look.
    
    Thank you

**Comment by salman90** [comment]
@jag-sekhon can you check sample [3-2) Protect and call a web API on Azure AD B2C](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/3-Authorization-II/2-call-api-b2c) . This sample demonstrates a todo-list (SPA) making (get, post, update, delete) calls to an ASP.NET Core API secured with Azure AD B2C. If the error persists after trying the sample, please share a piece of your code to reproduce the error.
