### ISSUE TITLE
Angular app needs admin approval when trying to access API

### ISSUE THREAD

**Issue by dmccolloughOneGas** [Azure-Samples/ms-identity-javascript-angular-tutorial#44]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [X] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [X ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ]   4) Deploy to Azure Storage and App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call a multi-tenant web API
    - [ ] 7-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 7-2) Call a web API using Proof of Possession tokens
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [X] question
    - [ ] feature request
    - [ ] documentation issue or request
```
I am having an issue with a Angular 12 app using MSALv2 based on the example at this location:
https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/3-Authorization-II/1-call-api

The Azure App Registration for the SPA asks for the following permissions:
Our API, access_as_user
Graph permissions:
User.read
User.read.All
User.ReadBasic.All
User.ReadWrite
User.ReadWrite.All

2 of the above permissions were needing admin consent required. When I run the angular 12 locally and navigate to http://localhost:4200 I can think click on the profile tab and fetch the Azure AD information. Once I see that working, I have added a tab that makes a post request to a API that we host internally. It's on a guarded (MsalGuard) route so it should be passing over the token.

I can't see if it completes because it prompts me and tells that the app needs admin approval. Well the app has admin approval so why is it asking me for this?

I have provided the angular code, however trying to provide the API code would be difficult as this is production code that I cannot share.

Thanks! We'll be in touch soon.
[Archive.zip](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/files/7781782/Archive.zip)

**Comment by Layne101** [comment]
When trying this [smaple](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/blob/main/3-Authorization-II/1-call-api/README.md#run-the-sample), I met the same issue here. 
<img width="505" alt="image" src="https://user-images.githubusercontent.com/69224018/155251265-d3b68e76-a703-4e0b-acd0-ef01b4f0bdb5.png">

**Comment by siyuniu-ms** [comment]
same here, any update on this?
