### ISSUE TITLE
Maintaining App Roles in both SPA and API

### ISSUE THREAD

**Issue by Thnslj** [Azure-Samples/ms-identity-javascript-angular-tutorial#45]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ]   4) Deploy to Azure Storage and App Service
    - [x] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call a multi-tenant web API
    - [ ] 7-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 7-2) Call a web API using Proof of Possession tokens
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [x] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

>Follow the tutorial step by step. 
>
> 
> It seems like you have to map users/groups to App Roles BOTH for the SPA and and API in the Enterprise Apps.
> 
> In our UI, we would like to conditionally render buttons/pages/menues  matching the users access to the underlying API. It is possible if we configure the App Roles in both the SPA and the API (like shown in this tutorial). However it seems fragile that the administrator will have to maintain the accesses in two places.
> 
> In this tutorial the angular app will look at the `idToken`'s roles, and the api will look at the `accessToken`'s roles. 
> 
> Is there a way to consolidate these accesses in one place? Or somehow pass the `App Roles` from the SPA to the API?

### Any log messages given by the failure

>

### Expected/desired behavior

>

### Library version

>

### Browser and version

> Not browser related

### Mention any other details that might be useful

> Same question was asked on stackoverflow by another user: https://stackoverflow.com/questions/62214073/azure-role-based-web-and-api-using-same-app-roles

**Comment by BGajda13** [comment]
I'm facing the same problem.

I haven't found any other better option than reading roles in App from access_token...

**Comment by Thnslj** [comment]
> I'm facing the same problem.
> 
> I haven't found any other better option than reading roles in App from access_token...

Hi @BGajda13 . I also asked the same question here, but still not a good solution: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4389

---

When are you reading the access_token? Do you immediately after login get an access_token and look in it? or do you try to call your api, then first then get the access_token?

**Comment by bastek338** [comment]
Hi @Thnslj, we use React in our project, but maybe this approach will work for you as well. 

```
import { useMsal } from '@azure/msal-react'
import { loginRequest } from '@shared/auth/authConfig' // loginRequest contains { scopes: [YOUR_SCOPE] }
import jwt_decode from 'jwt-decode'

const useGetTokenHook = () => {
 
   const { instance, accounts, inProgress } = useMsal()

    const getToken = async () => {
        try {
            const response = await instance.acquireTokenSilent({
                ...loginRequest,
                account: accounts[0],
            })
            const decodeToken: any = jwt_decode(response.accessToken)
        } catch (error) {
            console.error(error)
        }
    }

    const hasAccess = useMemo(() => {
        return hasUserCorrectRole(roles, accountRoles)
    }, [roles, accountRoles])

    useEffect(() => {
        if (inProgress === 'none' && accounts.length > 0) {
           getToken()
        }
    }, [inProgress, accounts, instance])
}

```

You can find more in these sources

[https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/acquire-token.md](url)
[https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md](url)
