### ISSUE TITLE
Question - multiple consents needed

### ISSUE THREAD

**Issue by jeromechrist** [Azure-Samples/ms-identity-javascript-angular-tutorial#6]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [x] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ]   4) Deploy to Azure Storage and App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call a multi-tenant web API
    - [ ] 7-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 7-2) Call a web API using Proof of Possession tokens
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [x] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

> follow the documentation for the scenario

Hello,

I went through the scenario 3-1 and i was wondering why do I have to consent 2 times ?

I had one popup after the Login
<img width="722" alt="010-consent" src="https://user-images.githubusercontent.com/2547646/119014555-61170c00-b998-11eb-83f5-8d5a79d57395.png">

And one when I first clicked the TodoList button

<img width="722" alt="012-todolist" src="https://user-images.githubusercontent.com/2547646/119014385-362cb800-b998-11eb-8697-2b6de522a8dc.png">

I was expecting to get only one consent

**Comment by derisen** [comment]
@jeromechrist this is expected. What happens here is called [dynamic consent](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#request-the-permissions-in-the-app-registration-portal) i.e. the app presents you with a consent screen only when the permission is actually needed. The first permission screen is for scopes that are requested during sign-in: `openid`, `profile `and `offline_access `(these are default OIDC scopes). The second screen is for the scope required for calling your web API (`access_as_user` in the sample). You get this screen later in the app when you are actually trying to call the web API.

**Comment by jeromechrist** [comment]
ah ok I get it.

all of this scope check dance is made my the MSAL library only on the client side ? Or with the combination of Identity.Web in the API ?

**Comment by derisen** [comment]
@jeromechrist that's right, this is carried out by MSAL Angular on the client side. Basically the user consents to the client app to access the web API on her behalf. The web API has no user interaction capability here, but if it was a user facing app, Identity.Web would have handled it (Identity.Web is a wrapper around MSAL .NET)

**Comment by jeromechrist** [comment]
Thank you :)

Great samples by the way, I really like that you covered a lot of useful scenarios
