### ISSUE TITLE
scenario 3 - protect and call web api on azure ad b2c - infinite loop

### ISSUE THREAD

**Issue by jeromechrist** [Azure-Samples/ms-identity-javascript-angular-tutorial#7]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [x] 3-2) Protect and call a web API on Azure AD B2C
    - [ ]   4) Deploy to Azure Storage and App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call a multi-tenant web API
    - [ ] 7-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 7-2) Call a web API using Proof of Possession tokens
```

## This issue is for a

```console
    - [x] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

> Follow the sample tutorial step by step

### Any log messages given by the failure

>

### Expected/desired behavior

> I should be able to access the web-api / edit my profile

### Library version

>

### Browser and version

> Safari?

### Mention any other details that might be useful

I can login fine (I had to go to the portal first and configure the sign in policy to allow the user to self reset his password) but then when i click the TodoList button it goes to an infinite loop (looks like login/logout)

https://user-images.githubusercontent.com/2547646/120226164-f5aa2580-c246-11eb-9565-9e3f29b98bd7.mov

here is my repo https://github.com/jeromechrist/repro-step-b2c

>

Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@jeromechrist thank you very much for the details and the repro link, I was able to reproduce the issue. I'll get back to you as soon as I figure this out.

**Comment by jeromechrist** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2547646/120395435-45ffb100-c335-11eb-8cc2-75c02adff755.png">

I just clicked that grant permission button and I can access the APIs feature fine.

But there is still a loop when I click on "Edit Profile"


https://user-images.githubusercontent.com/2547646/120396169-611ef080-c336-11eb-90d1-7491f3ca7699.mov

**Comment by derisen** [comment]
@jeromechrist strange, I can reproduce this with the edit user-flow you've set up, but not with my edit user-flow. I'm suspecting this is to do with your configuration. Have you configured any [user attributes and/or application claims](https://docs.microsoft.com/en-us/azure/active-directory-b2c/configure-user-input?pivots=b2c-user-flow)? It might be that there is no attribute/claim to edit, which might cause the edit screen not showing at all.

![ss](https://user-images.githubusercontent.com/13197548/120401082-0c5a8600-c2f4-11eb-89cb-8f252156531f.png)

**Comment by jeromechrist** [comment]
@derisen yep that was the case, I did selected claims in "Application claims" but no in "User attributes". After setting a few it works !
<img width="1440" alt="Screenshot 2021-06-02 at 15 13 16" src="https://user-images.githubusercontent.com/2547646/120486498-6707e680-c3b5-11eb-8ea7-b1c26415b0d7.png">
<img width="1440" alt="Screenshot 2021-06-02 at 15 13 36" src="https://user-images.githubusercontent.com/2547646/120486505-68d1aa00-c3b5-11eb-8312-9650af7ab777.png">

Thank you for helping troubleshoot the issue

**Comment by derisen** [comment]
@jeromechrist awesome! I'll update the sample README with the missing admin consent step and add some remarks about setting up user claims. Really appreciate all the details you provided in the issue -makes our lives easier : )

**Comment by jeromechrist** [comment]
@derisen heyyyyy sorry, it did resolve the edit profile part but the loop is back on the API :confused:

https://user-images.githubusercontent.com/2547646/120495382-f1077d80-c3bc-11eb-847c-7484a5ae0739.mov

**Comment by derisen** [comment]
@jeromechrist hmm, I'll check this with B2C team and get back to you. In the meantime, can you send me a network trace using [Fiddler](https://www.telerik.com/fiddler). My email is on my GitHub profile.

**Comment by jeromechrist** [comment]
hey @derisen, sorry for the delay, just for the heck of it I tried another browser and it looks like this bug is happening on Safari only, no issues on Edge (dev channel)

on Safari the bug repro is 100%


https://user-images.githubusercontent.com/2547646/120699728-12e22c80-c4b1-11eb-9cb4-635d08c897bc.mov

**Comment by derisen** [comment]
@jeromechrist Ok, I've just tested this on a Mac with Safari and I can reproduce it as well. 

At this point, it would be best to raise this issue in the [main MSAL.js repo](https://github.com/AzureAD/microsoft-authentication-library-for-js), as this is likely to do with the msal-angular itself rather than the sample. I can't seem to transfer it, can you please [create a bug report](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose) there?

**Comment by jeromechrist** [comment]
Yep, created there https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3713
