### ISSUE TITLE
   cd ../    cd API    dotnet run

### ISSUE THREAD

**Issue by subrem** [Azure-Samples/ms-identity-javascript-angular-tutorial#78]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ]   4) Deploy to Azure Storage and App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call a multi-tenant web API
    - [ ] 7-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 7-2) Call a web API using Proof of Possession tokens
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

>

### Any log messages given by the failure

>

### Expected/desired behavior

>

### Library version

>

### Browser and version

> Chrome, Edge, Firefox, Safari?

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by salman90** [comment]
Hi @subrem, please let us know which sample is causing the issue and provide us with more information about the error to replicate it.

**Comment by Layne101** [comment]
I guess he meant to this sample (https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/blob/main/3-Authorization-II/1-call-api/README.md#run-the-sample). I met it too.

**Comment by salman90** [comment]
[@Layne101](https://github.com/Layne101) and [@subrem](https://github.com/subrem), thanks for flagging this issue. We will update the doc as soon as possible. For now, please ``` cd API/TodoListAPI ``` after that ```dotnet run```
